In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "name": ['harry','rohan','shilf','shubh'],
    "marks": [92,38,45,15],
    "city":['rampur','kolkata','bareilly','antarctica']
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

    name  marks        city
0  harry     92      rampur
1  rohan     38     kolkata
2  shilf     45    bareilly
3  shubh     15  antarctica

In [5]:
df.to_csv('friends.csv')

In [6]:
df.to_csv('friends_indexfalse.csv',index= False)

In [7]:
df.to_csv('friends_indexfalse.csv',index=False)

In [8]:
df.describe()

           marks
count   4.000000
mean   47.500000
std    32.316147
min    15.000000
25%    32.250000
50%    41.500000
75%    56.750000
max    92.000000

In [9]:
dict1 ['marks'] [2]

45

In [10]:
dict1 ['marks'] [2] = 74

In [11]:
dict1 ['marks'] [2]

74

In [12]:
ser = pd.Series(np.random.rand(34))

In [13]:
ser

0     0.681684
1     0.344008
2     0.194629
3     0.151698
4     0.602501
5     0.172190
6     0.153916
7     0.676254
8     0.924827
9     0.830669
10    0.141982
11    0.328651
12    0.504850
13    0.600635
14    0.157008
15    0.854033
16    0.808874
17    0.218257
18    0.010647
19    0.709853
20    0.164074
21    0.233048
22    0.313465
23    0.589174
24    0.494694
25    0.264774
26    0.284984
27    0.069036
28    0.663792
29    0.705914
30    0.877645
31    0.198888
32    0.221851
33    0.680812
dtype: float64

In [14]:
type(ser)

pandas.core.series.Series

In [16]:
newdf =pd.DataFrame(np.random.rand(334,5), index=np.arange(334))

In [17]:
newdf.head()

          0         1         2         3         4
0  0.359971  0.025581  0.742508  0.553880  0.677276
1  0.435289  0.574044  0.749219  0.902268  0.558714
2  0.716697  0.691358  0.560703  0.130205  0.928539
3  0.416185  0.730714  0.473353  0.542369  0.782536
4  0.299482  0.811388  0.867460  0.115401  0.938057

In [18]:
newdf

            0         1         2         3         4
0    0.359971  0.025581  0.742508  0.553880  0.677276
1    0.435289  0.574044  0.749219  0.902268  0.558714
2    0.716697  0.691358  0.560703  0.130205  0.928539
3    0.416185  0.730714  0.473353  0.542369  0.782536
4    0.299482  0.811388  0.867460  0.115401  0.938057
..        ...       ...       ...       ...       ...
329  0.511967  0.777498  0.923184  0.258525  0.075046
330  0.158603  0.515863  0.321608  0.412280  0.213822
331  0.835393  0.279560  0.331407  0.793331  0.151034
332  0.122451  0.738907  0.836308  0.396587  0.347181
333  0.714610  0.940159  0.965583  0.203728  0.399338

[334 rows x 5 columns]

In [19]:
type(newdf)

pandas.core.frame.DataFrame

In [20]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.457558    0.499231    0.493076    0.485614    0.482434
std      0.273149    0.290568    0.276035    0.290188    0.292043
min      0.000185    0.000321    0.001186    0.002195    0.000160
25%      0.233596    0.265018    0.267989    0.221339    0.235966
50%      0.440703    0.494065    0.489809    0.477976    0.473440
75%      0.671930    0.759627    0.739650    0.758788    0.726335
max      0.996776    0.996993    0.997291    0.989740    0.996601

In [21]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [22]:
newdf.head()

          0         1         2         3         4
0  0.359971  0.025581  0.742508  0.553880  0.677276
1  0.435289  0.574044  0.749219  0.902268  0.558714
2  0.716697  0.691358  0.560703  0.130205  0.928539
3  0.416185  0.730714  0.473353  0.542369  0.782536
4  0.299482  0.811388  0.867460  0.115401  0.938057

In [23]:
newdf[0][0] = "Harshu"

C:\Users\harsh\AppData\Local\Temp\ipykernel_21156\3707062094.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "Harshu"
C:\Users\harsh\AppData\Local\Temp\ipykernel_21156\3707062094.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Harshu' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "Harshu"

In [24]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [25]:
newdf.Harshu

AttributeError: 'DataFrame' object has no attribute 'Harshu'

In [26]:
newdf.head()

          0         1         2         3         4
0    Harshu  0.025581  0.742508  0.553880  0.677276
1  0.435289  0.574044  0.749219  0.902268  0.558714
2  0.716697  0.691358  0.560703  0.130205  0.928539
3  0.416185  0.730714  0.473353  0.542369  0.782536
4  0.299482  0.811388  0.867460  0.115401  0.938057

In [27]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [28]:
newdf.coloumns

AttributeError: 'DataFrame' object has no attribute 'coloumns'

In [29]:
newdf.to_numpy()

array([['Harshu', 0.025580560635691807, 0.7425084995633158,
        0.5538800968937403, 0.6772761314403632],
       [0.43528921783929386, 0.5740439783595183, 0.7492188991363404,
        0.9022678378233888, 0.5587141101296378],
       [0.7166972388278915, 0.6913576149930344, 0.5607032573587301,
        0.13020541933893592, 0.9285385681703465],
       ...,
       [0.8353929501390369, 0.27956020580774943, 0.3314072621326236,
        0.7933313042366614, 0.15103396608183484],
       [0.12245141115481384, 0.7389073338016816, 0.8363079422266245,
        0.3965870068627524, 0.34718057208301456],
       [0.7146096037092453, 0.9401594020049164, 0.9655832355864051,
        0.20372796566380502, 0.3993375400304545]],
      shape=(334, 5), dtype=object)

In [31]:
newdf[0][0] = 0.5

In [32]:
newdf.head()

          0         1         2         3         4
0       0.5  0.025581  0.742508  0.553880  0.677276
1  0.435289  0.574044  0.749219  0.902268  0.558714
2  0.716697  0.691358  0.560703  0.130205  0.928539
3  0.416185  0.730714  0.473353  0.542369  0.782536
4  0.299482  0.811388  0.867460  0.115401  0.938057

In [34]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.5,0.435289,0.716697,0.416185,0.299482,0.542351,0.931544,0.511616,0.477641,0.441585,...,0.678959,0.852339,0.226625,0.248388,0.537976,0.511967,0.158603,0.835393,0.122451,0.71461
1,0.025581,0.574044,0.691358,0.730714,0.811388,0.278533,0.493319,0.711165,0.59212,0.450847,...,0.988765,0.499587,0.748092,0.261789,0.113085,0.777498,0.515863,0.27956,0.738907,0.940159
2,0.742508,0.749219,0.560703,0.473353,0.86746,0.790784,0.740768,0.863939,0.423779,0.353955,...,0.042094,0.072018,0.021565,0.235319,0.652915,0.923184,0.321608,0.331407,0.836308,0.965583
3,0.55388,0.902268,0.130205,0.542369,0.115401,0.271343,0.820278,0.198869,0.089577,0.255015,...,0.881456,0.594865,0.2817,0.014179,0.428502,0.258525,0.41228,0.793331,0.396587,0.203728
4,0.677276,0.558714,0.928539,0.782536,0.938057,0.143746,0.086937,0.43672,0.978972,0.391425,...,0.767994,0.342632,0.656119,0.474978,0.901134,0.075046,0.213822,0.151034,0.347181,0.399338

In [35]:
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333   0.71461  0.940159  0.965583  0.203728  0.399338
332  0.122451  0.738907  0.836308  0.396587  0.347181
331  0.835393  0.279560  0.331407  0.793331  0.151034
330  0.158603  0.515863  0.321608  0.412280  0.213822
329  0.511967  0.777498  0.923184  0.258525  0.075046
..        ...       ...       ...       ...       ...
4    0.299482  0.811388  0.867460  0.115401  0.938057
3    0.416185  0.730714  0.473353  0.542369  0.782536
2    0.716697  0.691358  0.560703  0.130205  0.928539
1    0.435289  0.574044  0.749219  0.902268  0.558714
0         0.5  0.025581  0.742508  0.553880  0.677276

[334 rows x 5 columns]

In [36]:
newdf.sort_index(axis=1,ascending=False)

            4         3         2         1         0
0    0.677276  0.553880  0.742508  0.025581       0.5
1    0.558714  0.902268  0.749219  0.574044  0.435289
2    0.928539  0.130205  0.560703  0.691358  0.716697
3    0.782536  0.542369  0.473353  0.730714  0.416185
4    0.938057  0.115401  0.867460  0.811388  0.299482
..        ...       ...       ...       ...       ...
329  0.075046  0.258525  0.923184  0.777498  0.511967
330  0.213822  0.412280  0.321608  0.515863  0.158603
331  0.151034  0.793331  0.331407  0.279560  0.835393
332  0.347181  0.396587  0.836308  0.738907  0.122451
333  0.399338  0.203728  0.965583  0.940159   0.71461

[334 rows x 5 columns]

In [37]:
newdf2 = newdf

In [38]:
newdf[0][0] =1256

In [39]:
newdf

            0         1         2         3         4
0        1256  0.025581  0.742508  0.553880  0.677276
1    0.435289  0.574044  0.749219  0.902268  0.558714
2    0.716697  0.691358  0.560703  0.130205  0.928539
3    0.416185  0.730714  0.473353  0.542369  0.782536
4    0.299482  0.811388  0.867460  0.115401  0.938057
..        ...       ...       ...       ...       ...
329  0.511967  0.777498  0.923184  0.258525  0.075046
330  0.158603  0.515863  0.321608  0.412280  0.213822
331  0.835393  0.279560  0.331407  0.793331  0.151034
332  0.122451  0.738907  0.836308  0.396587  0.347181
333   0.71461  0.940159  0.965583  0.203728  0.399338

[334 rows x 5 columns]