In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "name": ['harry','rohan','shilf','shubh'],
    "marks": [92,38,45,15],
    "city":['rampur','kolkata','bareilly','antarctica']
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

    name  marks        city
0  harry     92      rampur
1  rohan     38     kolkata
2  shilf     45    bareilly
3  shubh     15  antarctica

In [5]:
df.to_csv('friends.csv')

In [6]:
df.to_csv('friends_indexfalse.csv',index= False)

In [7]:
df.to_csv('friends_indexfalse.csv',index=False)

In [8]:
df.describe()

           marks
count   4.000000
mean   47.500000
std    32.316147
min    15.000000
25%    32.250000
50%    41.500000
75%    56.750000
max    92.000000

In [9]:
dict1 ['marks'] [2]

45

In [10]:
dict1 ['marks'] [2] = 74

In [11]:
dict1 ['marks'] [2]

74

In [12]:
ser = pd.Series(np.random.rand(34))

In [13]:
ser

0     0.703660
1     0.144995
2     0.657018
3     0.143248
4     0.915141
5     0.826630
6     0.239783
7     0.646774
8     0.264841
9     0.939324
10    0.529862
11    0.968825
12    0.696002
13    0.641044
14    0.013692
15    0.789031
16    0.432993
17    0.217712
18    0.002933
19    0.291623
20    0.135781
21    0.375585
22    0.318988
23    0.999979
24    0.313685
25    0.745956
26    0.518121
27    0.495990
28    0.168583
29    0.303377
30    0.240846
31    0.217289
32    0.742923
33    0.977239
dtype: float64

In [14]:
type(ser)

pandas.core.series.Series

In [15]:
newdf =pd.DataFrame(np.random.rand(334,5), index=np.arange(334))

In [16]:
newdf.head()

          0         1         2         3         4
0  0.550541  0.665140  0.756007  0.182738  0.706394
1  0.098624  0.012324  0.293710  0.194971  0.396447
2  0.435031  0.950987  0.828456  0.132217  0.455531
3  0.611919  0.361550  0.842232  0.624530  0.310812
4  0.425607  0.337228  0.725398  0.021320  0.203648

In [17]:
newdf

            0         1         2         3         4
0    0.550541  0.665140  0.756007  0.182738  0.706394
1    0.098624  0.012324  0.293710  0.194971  0.396447
2    0.435031  0.950987  0.828456  0.132217  0.455531
3    0.611919  0.361550  0.842232  0.624530  0.310812
4    0.425607  0.337228  0.725398  0.021320  0.203648
..        ...       ...       ...       ...       ...
329  0.095361  0.380219  0.937244  0.100700  0.732911
330  0.370701  0.320969  0.715633  0.183917  0.059932
331  0.648406  0.006270  0.493695  0.370009  0.123409
332  0.315536  0.745375  0.048878  0.345399  0.188353
333  0.152890  0.684375  0.788381  0.559356  0.113413

[334 rows x 5 columns]

In [18]:
type(newdf)

pandas.core.frame.DataFrame

In [19]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.512054    0.489027    0.480810    0.480590    0.475768
std      0.282956    0.296558    0.280295    0.278329    0.294850
min      0.000707    0.001440    0.002251    0.000108    0.001175
25%      0.289527    0.220921    0.241869    0.245219    0.230267
50%      0.504389    0.478609    0.449308    0.475891    0.438003
75%      0.749252    0.759397    0.724844    0.725592    0.738618
max      0.998733    0.997490    0.996129    0.998505    0.999141

In [20]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [21]:
newdf.head()

          0         1         2         3         4
0  0.550541  0.665140  0.756007  0.182738  0.706394
1  0.098624  0.012324  0.293710  0.194971  0.396447
2  0.435031  0.950987  0.828456  0.132217  0.455531
3  0.611919  0.361550  0.842232  0.624530  0.310812
4  0.425607  0.337228  0.725398  0.021320  0.203648

In [22]:
newdf[0][0] = "Harshu"

C:\Users\harsh\AppData\Local\Temp\ipykernel_9872\3707062094.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "Harshu"
C:\Users\harsh\AppData\Local\Temp\ipykernel_9872\3707062094.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Harshu' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "Harshu"

In [23]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [24]:
newdf.Harshu

AttributeError: 'DataFrame' object has no attribute 'Harshu'

In [ ]:
newdf.head()

In [ ]:
newdf.index

In [ ]:
newdf.coloumns

In [ ]:
newdf.to_numpy()

In [ ]:
newdf[0][0] = 0.5

In [ ]:
newdf.head()

In [ ]:
newdf.T

In [ ]:
newdf.sort_index(axis=0,ascending=False)

In [ ]:
newdf.sort_index(axis=1,ascending=False)

In [ ]:
newdf2 = newdf

In [ ]:
newdf[0][0] =1256

In [ ]:
newdf

In [ ]:
newdf.loc[0,0] = 654

In [25]:
newdf.head(2)

          0         1         2         3         4
0    Harshu  0.665140  0.756007  0.182738  0.706394
1  0.098624  0.012324  0.293710  0.194971  0.396447

In [26]:
newdf.coloumns = list("ABCDE")

C:\Users\harsh\AppData\Local\Temp\ipykernel_9872\2912145122.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  newdf.coloumns = list("ABCDE")

In [27]:
newdf.loc[0,0] =654

In [28]:
newdf.head()

          0         1         2         3         4
0       654  0.665140  0.756007  0.182738  0.706394
1  0.098624  0.012324  0.293710  0.194971  0.396447
2  0.435031  0.950987  0.828456  0.132217  0.455531
3  0.611919  0.361550  0.842232  0.624530  0.310812
4  0.425607  0.337228  0.725398  0.021320  0.203648

In [29]:
newdf.loc[[1,2],:]

          0         1         2         3         4
1  0.098624  0.012324  0.293710  0.194971  0.396447
2  0.435031  0.950987  0.828456  0.132217  0.455531

In [30]:
newdf.loc[(newdf[0]<0.3)]

            0         1         2         3         4
1    0.098624  0.012324  0.293710  0.194971  0.396447
6    0.218687  0.574890  0.252902  0.519567  0.190221
12   0.110956  0.575580  0.845230  0.887945  0.157543
15   0.000707  0.409006  0.574356  0.481715  0.004967
18   0.142047  0.048053  0.793153  0.200598  0.601935
..        ...       ...       ...       ...       ...
322  0.068289  0.371816  0.181997  0.147313  0.582781
324  0.133912  0.413812  0.111347  0.098822  0.226081
325  0.195772  0.030872  0.670825  0.553642  0.239456
329  0.095361  0.380219  0.937244  0.100700  0.732911
333   0.15289  0.684375  0.788381  0.559356  0.113413

[87 rows x 5 columns]

In [31]:
newdf.drop(0)

            0         1         2         3         4
1    0.098624  0.012324  0.293710  0.194971  0.396447
2    0.435031  0.950987  0.828456  0.132217  0.455531
3    0.611919  0.361550  0.842232  0.624530  0.310812
4    0.425607  0.337228  0.725398  0.021320  0.203648
5    0.805022  0.901122  0.063926  0.662313  0.108489
..        ...       ...       ...       ...       ...
329  0.095361  0.380219  0.937244  0.100700  0.732911
330  0.370701  0.320969  0.715633  0.183917  0.059932
331  0.648406  0.006270  0.493695  0.370009  0.123409
332  0.315536  0.745375  0.048878  0.345399  0.188353
333   0.15289  0.684375  0.788381  0.559356  0.113413

[333 rows x 5 columns]

In [32]:
df = pd.DataFrame(
    {         "name": ["Alfred", "Batman", "Catwoman"],
        "toy": [np.nan, "Batmobile", "Bullwhip"],
         "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT],
   }
 )

In [33]:
df.head

<bound method NDFrame.head of        name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT>

In [34]:
df.head()

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [35]:
df.dropna()

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [36]:
df.dropna(how='all')

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [38]:
df.dropna(how='all',axis=1)

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [39]:
 df.drop_duplicates(subset=["name])

SyntaxError: unterminated string literal (detected at line 1) (80502823.py, line 1)

In [42]:
 df.drop_duplicates(subset=['name'])

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [43]:
df()

TypeError: 'DataFrame' object is not callable

In [44]:
df.shape

(3, 3)

In [45]:
 df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   toy     2 non-null      object
 2   born    1 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(2)
memory usage: 204.0+ bytes

In [47]:
df['toy'].value_counts(dropna=False)

toy
NaN          1
Batmobile    1
Bullwhip     1
Name: count, dtype: int64

In [48]:
df.notnull()

   name    toy   born
0  True  False  False
1  True   True   True
2  True   True  False